# Generated by Django 3.1 on 2024-02-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20240212_0511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categorynam_name',
            new_name='category_name',
        ),
        migrations.AlterField(
            model_name='category',
            name='discription',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
